[package]
name = "quad_fighter"
version = "0.1.0"
authors = ["Srayan Jana <srayanj@uci.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = { git = "https://github.com/not-fl3/macroquad.git" }
